---
app_name: qnawebsite
repository: git@github.com:wolwire/qnawebsite.git
branch: master
paths:
  server: /home/pi
  local: /Users/mayank/qnawebsite
  config: /Users/mayank/qnawebsite/config
roles:
  app:
    - 192.168.0.107
default_env:
  RAILS_MASTER_KEY: 7ef6c65004913ef4eddcb47a4a4621be%
